# Generated by Django 4.2.2 on 2023-06-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=50)),
                ('addressDetails', models.JSONField()),
                ('WorkExperience', models.JSONField()),
                ('qualifications', models.JSONField()),
                ('projects', models.JSONField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
